{{- if .Values.ebpf.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: earthworm-agent
  namespace: {{ .Values.namespace }}
  labels:
    app: earthworm
    component: agent
spec:
  selector:
    matchLabels:
      app: earthworm
      component: agent
  template:
    metadata:
      labels:
        app: earthworm
        component: agent
    spec:
      hostPID: true
      serviceAccountName: earthworm
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: {{ .Values.agent.image }}
          securityContext:
            privileged: false
            capabilities:
              add:
                - CAP_BPF
                - CAP_SYS_ADMIN
                - CAP_PERFMON
          env:
            - name: EARTHWORM_RING_BUFFER_SIZE_KB
              value: "{{ .Values.ebpf.ringBufferSizeKB }}"
            - name: EARTHWORM_SERVER_URL
              value: "http://earthworm-server.{{ .Values.namespace }}.svc.cluster.local:8080"
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
{{- end }}
