apiVersion: v1
kind: ServiceAccount
metadata:
  name: earthworm
  namespace: {{ .Values.namespace }}
  labels:
    app: earthworm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: earthworm
  labels:
    app: earthworm
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: earthworm
  labels:
    app: earthworm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: earthworm
subjects:
  - kind: ServiceAccount
    name: earthworm
    namespace: {{ .Values.namespace }}
